In [1]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 3  2  3
 1  1  1
 1  3  2

In [3]:
B = A
C = copy(B)
[ B C]

3×6 Matrix{Int64}:
 3  2  3  3  2  3
 1  1  1  1  1  1
 1  3  2  1  3  2

In [4]:
A[1] = 17
[B C]

3×6 Matrix{Int64}:
 17  2  3  3  2  3
  1  1  1  1  1  1
  1  3  2  1  3  2

In [5]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [6]:
b = A*x

3-element Vector{Float64}:
 22.0
  3.0
  6.0

In [7]:
Asym = A + A'

3×3 Matrix{Int64}:
 34  3  4
  3  2  4
  4  4  4

In [8]:
Apd = A'A

3×3 Matrix{Int64}:
 291  38  54
  38  14  13
  54  13  14

In [9]:
A\b

3-element Vector{Float64}:
 1.0000000000000002
 1.0000000000000007
 0.9999999999999991

In [10]:
Atall = A[:, 1:2]
display(Atall)
Atall\b

3×2 Matrix{Int64}:
 17  2
  1  1
  1  3

2-element Vector{Float64}:
 1.0996197718631184
 1.6581749049429655

In [11]:
A = randn(3,3)

3×3 Matrix{Float64}:
 -0.169888  0.684905  -0.423491
 -0.451898  0.640471  -0.581883
 -0.357705  0.149999   0.30428

In [12]:
[A[:,1] A[:,1]]\b

2-element Vector{Float64}:
 -10.026221373184258
 -10.026221373184264

In [13]:
Ashort = A[1:2, :]
display(Ashort)
Ashort\b[1:2]

2×3 Matrix{Float64}:
 -0.169888  0.684905  -0.423491
 -0.451898  0.640471  -0.581883

3-element Vector{Float64}:
 53.537758338561375
 51.67031638238117
 10.13906656856792